# Generated by Django 6.0.1 on 2026-01-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaiable',
            new_name='available',
        ),
    ]
